// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.261
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CustomDateTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Date diff feature")]
    public partial class DateDiffFeatureFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DifferenceBetweenTwoDates.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Date diff feature", "In order to count days\r\nAs a Calendar\r\nI want to be told the number of days betwe" +
                    "en two dates", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in same month")]
        public virtual void DifferenceBetweenTwoDatesInSameMonth()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in same month", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have a date 21-01-2001");
#line 8
 testRunner.Then("the difference between it and another date 25-01-2001 should be 5");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in same month (2)")]
        public virtual void DifferenceBetweenTwoDatesInSameMonth2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in same month (2)", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 11
 testRunner.Given("I have a date 21-01-2001");
#line 12
 testRunner.Then("the difference between it and another date 26-01-2001 should be 6");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in same month in Reverse order")]
        public virtual void DifferenceBetweenTwoDatesInSameMonthInReverseOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in same month in Reverse order", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("I have a date 26-01-2001");
#line 16
 testRunner.Then("the difference between it and another date 21-01-2001 should be 6");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in same year but different months")]
        public virtual void DifferenceBetweenTwoDatesInSameYearButDifferentMonths()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in same year but different months", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("I have a date 21-01-2001");
#line 20
 testRunner.Then("the difference between it and another date 25-02-2001 should be 36");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in same year but different months (2)")]
        public virtual void DifferenceBetweenTwoDatesInSameYearButDifferentMonths2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in same year but different months (2)", ((string[])(null)));
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("I have a date 21-01-2001");
#line 24
 testRunner.Then("the difference between it and another date 25-03-2001 should be 64");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in same year but different months (3)")]
        public virtual void DifferenceBetweenTwoDatesInSameYearButDifferentMonths3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in same year but different months (3)", ((string[])(null)));
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("I have a date 21-01-2000");
#line 28
 testRunner.Then("the difference between it and another date 25-03-2000 should be 65");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in same year but different months in reverse order")]
        public virtual void DifferenceBetweenTwoDatesInSameYearButDifferentMonthsInReverseOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in same year but different months in reverse order", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("I have a date 25-03-2000");
#line 32
 testRunner.Then("the difference between it and another date 21-01-2000 should be 65");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in different years")]
        public virtual void DifferenceBetweenTwoDatesInDifferentYears()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in different years", ((string[])(null)));
#line 34
this.ScenarioSetup(scenarioInfo);
#line 35
 testRunner.Given("I have a date 21-01-2000");
#line 36
 testRunner.Then("the difference between it and another date 25-03-2001 should be 430");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in different years (2)")]
        public virtual void DifferenceBetweenTwoDatesInDifferentYears2()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in different years (2)", ((string[])(null)));
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
 testRunner.Given("I have a date 21-01-2001");
#line 40
 testRunner.Then("the difference between it and another date 25-03-2002 should be 429");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in different years (3)")]
        public virtual void DifferenceBetweenTwoDatesInDifferentYears3()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in different years (3)", ((string[])(null)));
#line 42
this.ScenarioSetup(scenarioInfo);
#line 43
 testRunner.Given("I have a date 29-01-2001");
#line 44
 testRunner.Then("the difference between it and another date 30-03-2011 should be 3713");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Difference between Two dates in different years in reverse order")]
        public virtual void DifferenceBetweenTwoDatesInDifferentYearsInReverseOrder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Difference between Two dates in different years in reverse order", ((string[])(null)));
#line 46
this.ScenarioSetup(scenarioInfo);
#line 47
 testRunner.Given("I have a date 25-03-2001");
#line 48
 testRunner.Then("the difference between it and another date 21-01-2000 should be 430");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
